# Generated by Django 4.2.2 on 2023-06-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('tipoProducto', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='tipoProducto')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='nombreTipo')),
            ],
        ),
        migrations.CreateModel(
            name='Plantita',
            fields=[
                ('idProducto', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='idProducto')),
                ('tituloProducto', models.CharField(max_length=50, verbose_name='tituloProducto')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenido.categoria', verbose_name='categoriaProduct')),
            ],
        ),
    ]
